# Generated by Django 4.2.4 on 2024-04-10 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0015_auto_20200516_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 4, 10, 11, 9, 23, 11096, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
